#!/usr/bin/env bash
# installs nginx and configures it to listen on port 80 and print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx

# Overwrite the default index file with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Start or reload nginx to apply changes
sudo service nginx start
